services:
  - type: web
    name: app-esienergia
    runtime: python
    plan: free
    pythonVersion: "3.11.9"
    buildCommand: |
      pip install --upgrade pip
      pip install setuptools==68.2.2
      pip install -r requirements.txt
    startCommand: python codigo/servidor.py
    healthCheckPath: /health-check
    autoDeploy: true
