"""Gerenciamento centralizado da conexao PostgreSQL/Supabase."""

from __future__ import annotations

import json
import os
import re
import sqlite3
import threading
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool


SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS admins (
    usuario TEXT PRIMARY KEY,
    token TEXT,
    raw_json TEXT NOT NULL,
    sort_order INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS empresas (
    codigo TEXT PRIMARY KEY,
    nome TEXT NOT NULL,
    ultimo_numero_cliente INTEGER NOT NULL DEFAULT 0,
    credenciais_json TEXT,
    raw_json TEXT NOT NULL,
    sort_order INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS constants (
    key TEXT PRIMARY KEY,
    value_json TEXT NOT NULL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS materials (
    key TEXT PRIMARY KEY,
    raw_json TEXT NOT NULL,
    sort_order INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS machine_catalog (
    type TEXT PRIMARY KEY,
    aplicacao TEXT,
    raw_json TEXT NOT NULL,
    sort_order INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS acessorios (
    tipo TEXT PRIMARY KEY,
    descricao TEXT,
    raw_json TEXT NOT NULL,
    sort_order INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS dutos (
    type TEXT PRIMARY KEY,
    descricao TEXT,
    raw_json TEXT NOT NULL,
    sort_order INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS tubos (
    polegadas TEXT PRIMARY KEY,
    mm REAL,
    valor REAL,
    raw_json TEXT NOT NULL,
    sort_order INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS obras (
    id TEXT PRIMARY KEY,
    nome TEXT,
    empresa_codigo TEXT,
    empresa_id TEXT,
    empresa_nome TEXT,
    numero_cliente_final INTEGER,
    raw_json TEXT NOT NULL,
    sort_order INTEGER NOT NULL,
    FOREIGN KEY (empresa_codigo) REFERENCES empresas(codigo) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS projetos (
    id TEXT PRIMARY KEY,
    obra_id TEXT NOT NULL,
    nome TEXT,
    raw_json TEXT NOT NULL,
    sort_order INTEGER NOT NULL,
    FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS salas (
    id TEXT PRIMARY KEY,
    projeto_id TEXT NOT NULL,
    nome TEXT,
    raw_json TEXT NOT NULL,
    sort_order INTEGER NOT NULL,
    FOREIGN KEY (projeto_id) REFERENCES projetos(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sala_maquinas (
    id TEXT PRIMARY KEY,
    sala_id TEXT NOT NULL,
    machine_type TEXT,
    raw_json TEXT NOT NULL,
    sort_order INTEGER NOT NULL,
    FOREIGN KEY (sala_id) REFERENCES salas(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sessions (
    session_id TEXT PRIMARY KEY,
    payload_json TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS admin_email_config (
    config_key TEXT PRIMARY KEY,
    email TEXT NOT NULL DEFAULT '',
    token TEXT NOT NULL DEFAULT '',
    nome TEXT NOT NULL DEFAULT '',
    smtp_host TEXT NOT NULL DEFAULT '',
    smtp_port INTEGER,
    use_tls INTEGER NOT NULL DEFAULT 1,
    updated_at TEXT
);

CREATE TABLE IF NOT EXISTS obra_notifications (
    obra_id TEXT PRIMARY KEY,
    fingerprint TEXT NOT NULL,
    last_subject TEXT NOT NULL DEFAULT '',
    last_message TEXT NOT NULL DEFAULT '',
    last_sent_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_empresas_sort_order ON empresas(sort_order);
CREATE INDEX IF NOT EXISTS idx_machine_catalog_sort_order ON machine_catalog(sort_order);
CREATE INDEX IF NOT EXISTS idx_obras_empresa_codigo ON obras(empresa_codigo);
CREATE INDEX IF NOT EXISTS idx_obras_empresa_codigo_numero_cliente ON obras(empresa_codigo, numero_cliente_final DESC);
CREATE INDEX IF NOT EXISTS idx_obras_sort_order ON obras(sort_order);
CREATE INDEX IF NOT EXISTS idx_obra_notifications_sent_at ON obra_notifications(last_sent_at);
CREATE INDEX IF NOT EXISTS idx_projetos_obra_id_sort ON projetos(obra_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_salas_projeto_id_sort ON salas(projeto_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_sala_maquinas_sala_id_sort ON sala_maquinas(sala_id, sort_order);
"""


IDENTITY_MARKERS = (
    "GENERATED BY DEFAULT AS IDENTITY",
    "GENERATED ALWAYS AS IDENTITY",
    "SERIAL",
    "BIGSERIAL",
    "SMALLSERIAL",
)

_POOLS = {}
_PROXIES = {}
_INITIALIZED_ROOTS = set()
_POOL_LOCK = threading.Lock()
_INITIALIZATION_LOCKS = {}
_WARMUP_LOCKS = {}
_WARMUP_STARTED_ROOTS = set()
_EMPRESAS_NUMERO_CLIENTE_COLUMN_CACHE = {}
_DOTENV_LOCK = threading.Lock()
_DOTENV_LOADED_PATHS = set()


@dataclass(frozen=True)
class SQLiteColumn:
    name: str
    declared_type: str
    not_null: bool
    default: str | None
    pk_position: int


@dataclass(frozen=True)
class SQLiteForeignKey:
    identifier: int
    seq: int
    table: str
    from_column: str
    to_column: str
    on_update: str
    on_delete: str


@dataclass(frozen=True)
class SQLiteIndex:
    name: str
    unique: bool
    columns: tuple[str, ...]


@dataclass(frozen=True)
class SQLiteTable:
    name: str
    columns: tuple[SQLiteColumn, ...]
    foreign_keys: tuple[SQLiteForeignKey, ...]
    indexes: tuple[SQLiteIndex, ...]
    create_sql: str
    source_row_count: int
    identity_columns: tuple[str, ...]


def get_database_path(project_root) -> Path:
    return Path(project_root) / "database" / "app.sqlite3"


def get_database_url(project_root=None) -> str:
    _load_environment_file(project_root)
    raw_url = str(os.environ.get("DATABASE_URL") or "").strip()
    if not raw_url:
        raise RuntimeError(
            "DATABASE_URL nao configurada. Defina a variavel de ambiente com a conexao PostgreSQL do Supabase."
        )
    return _enforce_ssl_mode(raw_url)


def get_connection(project_root):
    root_key = str(Path(project_root).resolve())
    with _POOL_LOCK:
        proxy = _PROXIES.get(root_key)
        if proxy is None:
            pool = ConnectionPool(
                conninfo=get_database_url(project_root),
                min_size=1,
                max_size=int(os.environ.get("DATABASE_POOL_MAX_SIZE", "10")),
                timeout=30,
                kwargs={
                    "autocommit": False,
                    "row_factory": dict_row,
                },
                open=True,
            )
            pool.wait()
            proxy = DatabaseConnectionProxy(pool)
            _POOLS[root_key] = pool
            _PROXIES[root_key] = proxy

    _initialize_database(project_root, root_key)
    return proxy


def execute_maintenance_statements(project_root, statements) -> None:
    root_key = str(Path(project_root).resolve())
    get_connection(project_root)
    pool = _POOLS[root_key]
    conn = pool.getconn()
    previous_autocommit = conn.autocommit

    try:
        try:
            conn.rollback()
        except Exception:
            pass

        conn.autocommit = True
        with conn.cursor() as cursor:
            for statement in statements or ():
                if str(statement or "").strip():
                    cursor.execute(str(statement))
    finally:
        try:
            conn.autocommit = previous_autocommit
        except Exception:
            pass

        try:
            if not conn.closed:
                pool.putconn(conn)
        except Exception:
            pass


def release_thread_connection(project_root=None) -> None:
    if project_root is not None:
        root_key = str(Path(project_root).resolve())
        proxy = _PROXIES.get(root_key)
        if proxy is not None:
            proxy.release()
        return

    for proxy in _PROXIES.values():
        proxy.release()


def start_connection_warmup(project_root) -> None:
    root_key = str(Path(project_root).resolve())
    warmup_lock = _WARMUP_LOCKS.setdefault(root_key, threading.Lock())

    with warmup_lock:
        if root_key in _WARMUP_STARTED_ROOTS:
            return
        _WARMUP_STARTED_ROOTS.add(root_key)

    warmup_thread = threading.Thread(
        target=_run_connection_warmup,
        args=(project_root,),
        daemon=True,
        name=f"postgres-warmup-{Path(root_key).name}",
    )
    warmup_thread.start()


def _run_connection_warmup(project_root) -> None:
    try:
        get_connection(project_root)
        release_thread_connection(project_root)
        print(" PostgreSQL pronto para uso.")
    except Exception as exc:
        print(f" Aviso no warmup do PostgreSQL: {exc}")


def migrate_sqlite_to_postgres(project_root):
    conn = get_connection(project_root)
    summary = {
        "database_url": _redact_database_url(get_database_url(project_root)),
        "sqlite_path": str(get_database_path(project_root).resolve()),
        "postgres_counts": _collect_postgres_counts(conn),
    }
    release_thread_connection(project_root)
    return summary


class DatabaseCursorProxy:
    def __init__(self, cursor):
        self._cursor = cursor

    def __enter__(self):
        self._cursor.__enter__()
        return self

    def __exit__(self, exc_type, exc, tb):
        return self._cursor.__exit__(exc_type, exc, tb)

    def execute(self, query, params=None):
        self._cursor.execute(_translate_query(query), params or ())
        return self

    def executemany(self, query, params_seq):
        self._cursor.executemany(_translate_query(query), params_seq)
        return self

    def __iter__(self):
        return iter(self._cursor)

    def __getattr__(self, name):
        return getattr(self._cursor, name)


class DatabaseConnectionProxy:
    def __init__(self, pool: ConnectionPool):
        self.pool = pool
        self._local = threading.local()

    def _get_or_acquire(self):
        conn = getattr(self._local, "conn", None)
        if conn is None or conn.closed:
            conn = self.pool.getconn()
            self._local.conn = conn
        return conn

    def cursor(self, *args, **kwargs):
        row_factory = kwargs.pop("row_factory", dict_row)
        return DatabaseCursorProxy(
            self._get_or_acquire().cursor(*args, row_factory=row_factory, **kwargs)
        )

    def execute(self, query, params=None):
        cursor = self.cursor()
        cursor.execute(query, params)
        return cursor

    def commit(self):
        conn = getattr(self._local, "conn", None)
        if conn is not None and not conn.closed:
            conn.commit()

    def rollback(self):
        conn = getattr(self._local, "conn", None)
        if conn is not None and not conn.closed:
            conn.rollback()

    def release(self):
        conn = getattr(self._local, "conn", None)
        if conn is None:
            return

        try:
            if not conn.closed:
                try:
                    conn.rollback()
                except Exception:
                    pass
                self.pool.putconn(conn)
        finally:
            self._local.conn = None


def _initialize_database(project_root, root_key: str) -> None:
    init_lock = _INITIALIZATION_LOCKS.setdefault(root_key, threading.Lock())
    with init_lock:
        if root_key in _INITIALIZED_ROOTS:
            return

        pool = _POOLS[root_key]
        with pool.connection() as conn:
            _execute_statements(conn, SCHEMA_SQL)
            conn.commit()

        _INITIALIZED_ROOTS.add(root_key)


def _execute_statements(conn, sql_script: str) -> None:
    statements = [statement.strip() for statement in sql_script.split(";") if statement.strip()]
    with conn.cursor() as cursor:
        for statement in statements:
            cursor.execute(statement)


def has_empresas_numero_cliente_column(project_root=None, conn=None) -> bool:
    root_key = None
    if project_root is not None:
        root_key = str(Path(project_root).resolve())
        cached = _EMPRESAS_NUMERO_CLIENTE_COLUMN_CACHE.get(root_key)
        if cached is not None:
            return bool(cached)

    connection = conn or get_connection(project_root)
    with connection.cursor(row_factory=dict_row) as cursor:
        cursor.execute(
            """
            SELECT EXISTS(
                SELECT 1
                FROM pg_attribute
                WHERE attrelid = to_regclass(current_schema() || '.empresas')
                  AND attname = %s
                  AND NOT attisdropped
            ) AS has_column
            """,
            ("ultimo_numero_cliente",),
        )
        row = cursor.fetchone()

    has_column = bool(row and row.get("has_column"))
    if root_key is not None:
        _EMPRESAS_NUMERO_CLIENTE_COLUMN_CACHE[root_key] = has_column
    return has_column


def _migrate_sqlite_if_needed(conn, project_root) -> None:
    sqlite_path = get_database_path(project_root).resolve()
    if not sqlite_path.exists():
        return

    source_signature = _build_sqlite_signature(sqlite_path)
    with conn.cursor(row_factory=dict_row) as cursor:
        cursor.execute("SELECT pg_advisory_lock(hashtext(%s))", ("esi_sqlite_migration",))

    try:
        sqlite_tables = _load_sqlite_tables(sqlite_path)
        if not sqlite_tables:
            return

        table_counts = {table.name: table.source_row_count for table in sqlite_tables}
        existing_state = _load_migration_state(conn, source_signature)
        current_counts = _collect_postgres_counts(conn, [table.name for table in sqlite_tables])

        if existing_state is not None:
            if current_counts == table_counts:
                return
            raise RuntimeError(
                "O banco PostgreSQL possui registro de migracao do SQLite, mas a contagem atual diverge do esperado."
            )

        if any(count > 0 for count in current_counts.values()):
            if current_counts == table_counts:
                _store_migration_state(conn, source_signature, sqlite_path, table_counts)
                return
            raise RuntimeError(
                "O banco PostgreSQL ja contem dados e nao corresponde ao SQLite local. A migracao automatica foi abortada para evitar duplicacao."
            )

        for table in sqlite_tables:
            if not _postgres_table_exists(conn, table.name):
                _create_table_from_sqlite_definition(conn, table)

        ordered_tables = _sort_tables_by_dependency(sqlite_tables)
        _copy_sqlite_data(conn, sqlite_path, ordered_tables)
        _reset_identity_sequences(conn, ordered_tables)

        migrated_counts = _collect_postgres_counts(conn, [table.name for table in ordered_tables])
        if migrated_counts != table_counts:
            raise RuntimeError(
                f"Migracao concluida com contagem divergente. SQLite={table_counts} PostgreSQL={migrated_counts}"
            )

        _store_migration_state(conn, source_signature, sqlite_path, table_counts)
    except Exception:
        conn.rollback()
        raise
    finally:
        try:
            with conn.cursor() as cursor:
                cursor.execute(
                    "SELECT pg_advisory_unlock(hashtext(%s))",
                    ("esi_sqlite_migration",),
                )
        except Exception:
            pass


def _load_migration_state(conn, source_signature: str):
    with conn.cursor(row_factory=dict_row) as cursor:
        cursor.execute(
            """
            SELECT source_signature, table_counts_json
            FROM sqlite_migration_state
            WHERE source_signature = %s
            """,
            (source_signature,),
        )
        return cursor.fetchone()


def _store_migration_state(conn, source_signature: str, sqlite_path: Path, table_counts: dict[str, int]) -> None:
    stat_result = sqlite_path.stat()
    with conn.cursor() as cursor:
        cursor.execute(
            """
            INSERT INTO sqlite_migration_state(
                source_signature,
                sqlite_path,
                sqlite_size,
                sqlite_mtime_ns,
                table_counts_json
            )
            VALUES(%s, %s, %s, %s, %s::jsonb)
            ON CONFLICT(source_signature) DO UPDATE SET
                sqlite_path = EXCLUDED.sqlite_path,
                sqlite_size = EXCLUDED.sqlite_size,
                sqlite_mtime_ns = EXCLUDED.sqlite_mtime_ns,
                table_counts_json = EXCLUDED.table_counts_json,
                migrated_at = CURRENT_TIMESTAMP
            """,
            (
                source_signature,
                str(sqlite_path),
                stat_result.st_size,
                stat_result.st_mtime_ns,
                json.dumps(table_counts, ensure_ascii=False),
            ),
        )


def _load_sqlite_tables(sqlite_path: Path) -> list[SQLiteTable]:
    sqlite_conn = sqlite3.connect(str(sqlite_path))
    sqlite_conn.row_factory = sqlite3.Row
    try:
        tables = []
        sqlite_tables = sqlite_conn.execute(
            """
            SELECT name, sql
            FROM sqlite_master
            WHERE type = 'table'
              AND name NOT LIKE 'sqlite_%'
            ORDER BY name
            """
        ).fetchall()

        for table_row in sqlite_tables:
            table_name = str(table_row["name"])
            create_sql = str(table_row["sql"] or "").strip()
            columns = tuple(
                SQLiteColumn(
                    name=str(row["name"]),
                    declared_type=str(row["type"] or ""),
                    not_null=bool(row["notnull"]),
                    default=row["dflt_value"],
                    pk_position=int(row["pk"] or 0),
                )
                for row in sqlite_conn.execute(f'PRAGMA table_info("{table_name}")').fetchall()
            )
            foreign_keys = tuple(
                SQLiteForeignKey(
                    identifier=int(row["id"]),
                    seq=int(row["seq"]),
                    table=str(row["table"]),
                    from_column=str(row["from"]),
                    to_column=str(row["to"]),
                    on_update=str(row["on_update"] or "NO ACTION"),
                    on_delete=str(row["on_delete"] or "NO ACTION"),
                )
                for row in sqlite_conn.execute(f'PRAGMA foreign_key_list("{table_name}")').fetchall()
            )

            indexes = []
            for index_row in sqlite_conn.execute(f'PRAGMA index_list("{table_name}")').fetchall():
                if str(index_row["origin"]) == "pk":
                    continue
                index_name = str(index_row["name"])
                index_columns = tuple(
                    str(info_row["name"])
                    for info_row in sqlite_conn.execute(f'PRAGMA index_info("{index_name}")').fetchall()
                    if info_row["name"]
                )
                if not index_columns:
                    continue
                indexes.append(
                    SQLiteIndex(
                        name=index_name,
                        unique=bool(index_row["unique"]),
                        columns=index_columns,
                    )
                )

            row_count = int(
                sqlite_conn.execute(f'SELECT COUNT(*) AS count FROM "{table_name}"').fetchone()["count"]
            )
            identity_columns = tuple(
                column.name
                for column in columns
                if _is_identity_candidate(column, create_sql)
            )

            tables.append(
                SQLiteTable(
                    name=table_name,
                    columns=columns,
                    foreign_keys=foreign_keys,
                    indexes=tuple(indexes),
                    create_sql=create_sql,
                    source_row_count=row_count,
                    identity_columns=identity_columns,
                )
            )

        return tables
    finally:
        sqlite_conn.close()


def _sort_tables_by_dependency(tables: list[SQLiteTable]) -> list[SQLiteTable]:
    table_map = {table.name: table for table in tables}
    dependencies = {
        table.name: {
            fk.table
            for fk in table.foreign_keys
            if fk.table in table_map and fk.table != table.name
        }
        for table in tables
    }

    ordered_names = []
    ready = sorted(name for name, deps in dependencies.items() if not deps)

    while ready:
        current = ready.pop(0)
        ordered_names.append(current)
        for name, deps in dependencies.items():
            if current in deps:
                deps.remove(current)
                if not deps and name not in ordered_names and name not in ready:
                    ready.append(name)
                    ready.sort()

    if len(ordered_names) != len(tables):
        remaining = [table.name for table in tables if table.name not in ordered_names]
        ordered_names.extend(sorted(remaining))

    return [table_map[name] for name in ordered_names]


def _postgres_table_exists(conn, table_name: str) -> bool:
    with conn.cursor(row_factory=dict_row) as cursor:
        cursor.execute("SELECT to_regclass(%s) AS regclass", (table_name,))
        row = cursor.fetchone()
        return bool(row and row["regclass"])


def _create_table_from_sqlite_definition(conn, table: SQLiteTable) -> None:
    primary_keys = sorted(
        (column for column in table.columns if column.pk_position > 0),
        key=lambda column: column.pk_position,
    )
    single_identity_pk = (
        len(primary_keys) == 1 and primary_keys[0].name in set(table.identity_columns)
    )

    column_definitions = []
    for column in table.columns:
        parts = [_quote_identifier(column.name)]

        if single_identity_pk and column.name == primary_keys[0].name:
            parts.append("INTEGER GENERATED BY DEFAULT AS IDENTITY")
        else:
            parts.append(_map_sqlite_type_to_postgres(column.declared_type))
            if column.default is not None:
                parts.append(f"DEFAULT {_translate_default_value(column.default)}")

        if column.not_null:
            parts.append("NOT NULL")

        if len(primary_keys) == 1 and column.name == primary_keys[0].name:
            parts.append("PRIMARY KEY")

        column_definitions.append(" ".join(parts))

    if len(primary_keys) > 1:
        pk_columns = ", ".join(_quote_identifier(column.name) for column in primary_keys)
        column_definitions.append(f"PRIMARY KEY ({pk_columns})")

    foreign_keys_by_id = {}
    for foreign_key in table.foreign_keys:
        foreign_keys_by_id.setdefault(foreign_key.identifier, []).append(foreign_key)

    for fk_items in foreign_keys_by_id.values():
        ordered = sorted(fk_items, key=lambda item: item.seq)
        from_columns = ", ".join(_quote_identifier(item.from_column) for item in ordered)
        to_columns = ", ".join(_quote_identifier(item.to_column) for item in ordered)
        reference_table = _quote_identifier(ordered[0].table)
        on_delete = ordered[0].on_delete or "NO ACTION"
        on_update = ordered[0].on_update or "NO ACTION"
        column_definitions.append(
            f"FOREIGN KEY ({from_columns}) REFERENCES {reference_table} ({to_columns}) ON DELETE {on_delete} ON UPDATE {on_update}"
        )

    create_table_sql = (
        f"CREATE TABLE IF NOT EXISTS {_quote_identifier(table.name)} (\n    "
        + ",\n    ".join(column_definitions)
        + "\n)"
    )

    with conn.cursor() as cursor:
        cursor.execute(create_table_sql)
        for index in table.indexes:
            index_columns = ", ".join(_quote_identifier(column) for column in index.columns)
            unique_keyword = "UNIQUE " if index.unique else ""
            cursor.execute(
                f"CREATE {unique_keyword}INDEX IF NOT EXISTS {_quote_identifier(index.name)} "
                f"ON {_quote_identifier(table.name)} ({index_columns})"
            )


def _copy_sqlite_data(conn, sqlite_path: Path, tables: list[SQLiteTable]) -> None:
    sqlite_conn = sqlite3.connect(str(sqlite_path))
    sqlite_conn.row_factory = sqlite3.Row
    try:
        with conn.cursor() as cursor:
            for table in tables:
                if table.source_row_count == 0:
                    continue

                column_names = [column.name for column in table.columns]
                quoted_columns = ", ".join(_quote_identifier(name) for name in column_names)
                placeholders = ", ".join(["%s"] * len(column_names))
                insert_sql = (
                    f"INSERT INTO {_quote_identifier(table.name)} ({quoted_columns}) "
                    f"VALUES ({placeholders})"
                )

                source_rows = sqlite_conn.execute(
                    f'SELECT {quoted_columns} FROM "{table.name}"'
                ).fetchall()
                batch = [tuple(row[column_name] for column_name in column_names) for row in source_rows]
                cursor.executemany(insert_sql, batch)
    finally:
        sqlite_conn.close()


def _reset_identity_sequences(conn, tables: list[SQLiteTable]) -> None:
    with conn.cursor(row_factory=dict_row) as cursor:
        for table in tables:
            for column_name in table.identity_columns:
                cursor.execute(
                    "SELECT pg_get_serial_sequence(%s, %s) AS sequence_name",
                    (table.name, column_name),
                )
                sequence_row = cursor.fetchone()
                if not sequence_row or not sequence_row["sequence_name"]:
                    continue

                cursor.execute(
                    f"SELECT COALESCE(MAX({_quote_identifier(column_name)}), 0) AS max_value "
                    f"FROM {_quote_identifier(table.name)}"
                )
                max_row = cursor.fetchone()
                max_value = int(max_row["max_value"] or 0)
                cursor.execute(
                    "SELECT setval(%s, %s, %s)",
                    (
                        sequence_row["sequence_name"],
                        max_value if max_value > 0 else 1,
                        max_value > 0,
                    ),
                )


def _collect_postgres_counts(conn, table_names=None) -> dict[str, int]:
    if table_names is None:
        with conn.cursor(row_factory=dict_row) as cursor:
            cursor.execute(
                """
                SELECT table_name
                FROM information_schema.tables
                WHERE table_schema = 'public'
                  AND table_type = 'BASE TABLE'
                ORDER BY table_name
                """
            )
            table_names = [row["table_name"] for row in cursor.fetchall()]

    counts = {}
    with conn.cursor(row_factory=dict_row) as cursor:
        for table_name in table_names:
            if not _postgres_table_exists(conn, str(table_name)):
                counts[str(table_name)] = 0
                continue
            cursor.execute(
                f"SELECT COUNT(*) AS count FROM {_quote_identifier(table_name)}"
            )
            row = cursor.fetchone()
            counts[str(table_name)] = int(row["count"] if row else 0)
    return counts


def _map_sqlite_type_to_postgres(declared_type: str) -> str:
    normalized = str(declared_type or "").strip().upper()
    if not normalized:
        return "TEXT"
    if "INT" in normalized:
        return "INTEGER"
    if any(token in normalized for token in ("CHAR", "CLOB", "TEXT")):
        return "TEXT"
    if "BLOB" in normalized:
        return "BYTEA"
    if any(token in normalized for token in ("REAL", "FLOA", "DOUB")):
        return "REAL"
    if "BOOL" in normalized:
        return "BOOLEAN"
    if any(token in normalized for token in ("NUMERIC", "DECIMAL")):
        return "NUMERIC"
    if "DATE" in normalized or "TIME" in normalized:
        return "TIMESTAMP"
    return "TEXT"


def _translate_default_value(default_value) -> str:
    value = str(default_value).strip()
    if not value:
        return "NULL"
    return value


def _is_identity_candidate(column: SQLiteColumn, create_sql: str) -> bool:
    if column.pk_position != 1:
        return False
    if "INT" not in str(column.declared_type or "").upper():
        return False
    create_sql_upper = str(create_sql or "").upper()
    return (
        "AUTOINCREMENT" in create_sql_upper
        or "INTEGER PRIMARY KEY" in create_sql_upper
    )


def _build_sqlite_signature(sqlite_path: Path) -> str:
    stat_result = sqlite_path.stat()
    return f"{sqlite_path.resolve()}::{stat_result.st_size}::{stat_result.st_mtime_ns}"


def _quote_identifier(identifier: str) -> str:
    return '"' + str(identifier).replace('"', '""') + '"'


def _translate_query(query: str) -> str:
    translated = str(query)
    translated = translated.replace("?", "%s")
    insert_or_ignore = bool(
        re.search(r"INSERT\s+OR\s+IGNORE\s+INTO", translated, flags=re.IGNORECASE)
    )
    translated = re.sub(
        r"INSERT\s+OR\s+IGNORE\s+INTO",
        "INSERT INTO",
        translated,
        flags=re.IGNORECASE,
    )
    if insert_or_ignore and "ON CONFLICT" not in translated.upper():
        translated = translated.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
    return translated


def _enforce_ssl_mode(database_url: str) -> str:
    parsed = urlsplit(database_url)
    query = dict(parse_qsl(parsed.query, keep_blank_values=True))
    query["sslmode"] = "require"
    secure_query = urlencode(query)
    return urlunsplit((parsed.scheme, parsed.netloc, parsed.path, secure_query, parsed.fragment))


def _redact_database_url(database_url: str) -> str:
    parsed = urlsplit(database_url)
    if "@" not in parsed.netloc:
        return database_url
    credentials, host = parsed.netloc.rsplit("@", 1)
    if ":" in credentials:
        username, _ = credentials.split(":", 1)
        credentials = f"{username}:***"
    return urlunsplit((parsed.scheme, f"{credentials}@{host}", parsed.path, parsed.query, parsed.fragment))


def _load_environment_file(project_root=None) -> None:
    candidate_paths = []
    if project_root is not None:
        resolved_root = Path(project_root).resolve()
        candidate_paths.extend(
            [
                resolved_root / ".env",
                resolved_root.parent / ".env",
            ]
        )
    else:
        current_dir = Path.cwd().resolve()
        candidate_paths.extend(
            [
                current_dir / ".env",
                current_dir.parent / ".env",
            ]
        )

    seen = set()
    unique_candidates = []
    for candidate in candidate_paths:
        candidate_str = str(candidate)
        if candidate_str in seen:
            continue
        seen.add(candidate_str)
        unique_candidates.append(candidate)

    with _DOTENV_LOCK:
        for env_path in unique_candidates:
            env_key = str(env_path)
            if env_key in _DOTENV_LOADED_PATHS:
                continue
            _DOTENV_LOADED_PATHS.add(env_key)
            if not env_path.exists():
                continue
            for raw_line in env_path.read_text(encoding="utf-8").splitlines():
                line = raw_line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, value = line.split("=", 1)
                key = key.strip()
                value = value.strip().strip('"').strip("'")
                if key and key not in os.environ:
                    os.environ[key] = value
